/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Glumac;
import domen.Popularnost;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import kontroler.KontrolerKorisnickogInterfejsa;

/**
 *
 * @author Luka
 */
public class formaObrisiGlumca extends javax.swing.JFrame {
    int x,y;    
    Glumac glumac;
    /**
     * Creates new form formaObrisiGlumca
     */
    public formaObrisiGlumca(Glumac g) {
        initComponents();
        popuniKombo();
        unesipodatke(g);
        glumac = g;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cbPol = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOpis = new javax.swing.JTextArea();
        txtAdresa = new javax.swing.JTextField();
        txtDatumRodjenja = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbPopularnost = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPrezime = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtIme = new javax.swing.JTextField();
        btnOdustani = new javax.swing.JLabel();
        btnObrisi = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forme/close5.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(660, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbPol.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbPol.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbPol.setEnabled(false);
        jPanel1.add(cbPol, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 138, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Popularnost: ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 110, 20));

        txtOpis.setColumns(20);
        txtOpis.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtOpis.setRows(5);
        txtOpis.setEnabled(false);
        jScrollPane1.setViewportView(txtOpis);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 250, 110));

        txtAdresa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtAdresa.setEnabled(false);
        jPanel1.add(txtAdresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 138, -1));

        txtDatumRodjenja.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDatumRodjenja.setEnabled(false);
        jPanel1.add(txtDatumRodjenja, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 138, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Datum rodjenja: ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 110, 20));

        cbPopularnost.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbPopularnost.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbPopularnost.setEnabled(false);
        jPanel1.add(cbPopularnost, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 138, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Prezime: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 110, 20));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Ime: ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 110, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Opis: ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 50, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Adresa: ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 110, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Pol: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 110, 20));

        txtPrezime.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPrezime.setEnabled(false);
        jPanel1.add(txtPrezime, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 138, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("(dd.MM.yyyy)");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, -1, -1));

        txtIme.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtIme.setEnabled(false);
        jPanel1.add(txtIme, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 138, -1));

        btnOdustani.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forme/button_odustani (2).png"))); // NOI18N
        btnOdustani.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOdustaniMouseClicked(evt);
            }
        });
        jPanel1.add(btnOdustani, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, -1, -1));

        btnObrisi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forme/button_obrisi (1).png"))); // NOI18N
        btnObrisi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnObrisiMouseClicked(evt);
            }
        });
        jPanel1.add(btnObrisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forme/poz.png"))); // NOI18N
        jLabel10.setText("jLabel10");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 700, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        int xx = evt.getXOnScreen();
        int yy = evt.getYOnScreen();
        this.setLocation(xx-x, yy-y);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void btnOdustaniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOdustaniMouseClicked
        dispose();
    }//GEN-LAST:event_btnOdustaniMouseClicked

    private void btnObrisiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnObrisiMouseClicked
        KontrolerKorisnickogInterfejsa.getInstanca().obrisiGlumca(glumac);
    }//GEN-LAST:event_btnObrisiMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(formaObrisiGlumca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(formaObrisiGlumca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(formaObrisiGlumca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(formaObrisiGlumca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new formaObrisiGlumca().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnObrisi;
    private javax.swing.JLabel btnOdustani;
    private javax.swing.JComboBox cbPol;
    private javax.swing.JComboBox cbPopularnost;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtAdresa;
    private javax.swing.JTextField txtDatumRodjenja;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextArea txtOpis;
    private javax.swing.JTextField txtPrezime;
    // End of variables declaration//GEN-END:variables

    private void popuniKombo() {
        cbPol.removeAllItems();
        cbPol.addItem("musko");
        cbPol.addItem("zensko");
        
        cbPopularnost.removeAllItems();
        ArrayList<Popularnost> pop = KontrolerKorisnickogInterfejsa.getInstanca().vratiPopularnost();
        for (Popularnost p : pop) {
            cbPopularnost.addItem(p);
        }
    }

    private void unesipodatke(Glumac g) {
        txtIme.setText(g.getIme());
        txtPrezime.setText(g.getPrezime());
        if(g.getPol().equals("zensko")){
            cbPol.setSelectedIndex(1);
        }else{
            cbPol.setSelectedIndex(0);
        }
        txtAdresa.setText(g.getAdresa());
        DateFormat df = new SimpleDateFormat("dd.MM.yyyy");
        String datum = df.format(g.getDatumRodjenja());
        txtDatumRodjenja.setText(datum);
        txtOpis.setText(g.getOpis());
        cbPopularnost.setSelectedIndex(g.getPopularnost().getPopularnostID()-1);
        
    }
}
