/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Popularnost;
import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import kontroler.KontrolerKorisnickogInterfejsa;
import static kontroler.KontrolerKorisnickogInterfejsa.formaUbaciGlumca;

/**
 *
 * @author Luka
 */
public class formaUbaciiGlumca extends javax.swing.JFrame {

    int x,y;
    /**
     * Creates new form formaObradiGlumca
     */
    public formaUbaciiGlumca() {
        initComponents();
        popuniKombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtAdresa = new javax.swing.JTextField();
        txtDatumRodjenja = new javax.swing.JTextField();
        cbPopularnost = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbPol = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOpis = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        txtIme = new javax.swing.JTextField();
        txtPrezime = new javax.swing.JTextField();
        btnUbaci = new javax.swing.JLabel();
        btnOdustani = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forme/close5.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(660, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Ime: ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 80, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Prezime: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 80, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Pol: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 80, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Adresa: ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 80, 20));

        txtAdresa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtAdresa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAdresaFocusLost(evt);
            }
        });
        jPanel1.add(txtAdresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 138, -1));

        txtDatumRodjenja.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDatumRodjenja.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDatumRodjenjaFocusLost(evt);
            }
        });
        jPanel1.add(txtDatumRodjenja, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 138, -1));

        cbPopularnost.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbPopularnost.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbPopularnost, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 138, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Datum rodjenja: ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 110, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Popularnost: ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 100, 20));

        cbPol.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbPol.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbPol, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 138, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Opis: ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 50, 20));

        txtOpis.setColumns(20);
        txtOpis.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtOpis.setRows(5);
        txtOpis.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtOpisFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(txtOpis);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 250, 110));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("(dd.MM.yyyy)");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, -1, -1));

        txtIme.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtIme.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtImeFocusLost(evt);
            }
        });
        jPanel1.add(txtIme, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 138, -1));

        txtPrezime.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPrezime.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPrezimeFocusLost(evt);
            }
        });
        jPanel1.add(txtPrezime, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 138, -1));

        btnUbaci.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forme/button_ubaci (1).png"))); // NOI18N
        btnUbaci.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUbaciMouseClicked(evt);
            }
        });
        jPanel1.add(btnUbaci, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, -1, -1));

        btnOdustani.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forme/button_odustani (2).png"))); // NOI18N
        btnOdustani.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOdustaniMouseClicked(evt);
            }
        });
        jPanel1.add(btnOdustani, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forme/poz.png"))); // NOI18N
        jLabel10.setText("jLabel10");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 700, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        int xx = evt.getXOnScreen();
        int yy = evt.getYOnScreen();
        this.setLocation(xx-x, yy-y);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void btnUbaciMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUbaciMouseClicked
        KontrolerKorisnickogInterfejsa.getInstanca().ubaciGlumca(txtIme.getText(),txtPrezime.getText(),(String)cbPol.getSelectedItem(),txtAdresa.getText(),txtDatumRodjenja.getText(),txtOpis.getText(),(Popularnost)cbPopularnost.getSelectedItem());
    }//GEN-LAST:event_btnUbaciMouseClicked

    private void btnOdustaniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOdustaniMouseClicked
        dispose();
    }//GEN-LAST:event_btnOdustaniMouseClicked

    private void txtImeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtImeFocusLost
        if(txtIme.getText().isEmpty()){
            txtIme.setBackground(new Color(255, 168, 168));
        }else{
            txtIme.setBackground(Color.white);
        }   
    }//GEN-LAST:event_txtImeFocusLost

    private void txtPrezimeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPrezimeFocusLost
        if(txtPrezime.getText().isEmpty()){
            txtPrezime.setBackground(new Color(255, 168, 168));
        }else{
            txtPrezime.setBackground(Color.white);
        }  
    }//GEN-LAST:event_txtPrezimeFocusLost

    private void txtAdresaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAdresaFocusLost
        if(txtAdresa.getText().isEmpty()){
            txtAdresa.setBackground(new Color(255, 168, 168));
        }else{
            txtAdresa.setBackground(Color.white);
        }  
    }//GEN-LAST:event_txtAdresaFocusLost

    private void txtDatumRodjenjaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDatumRodjenjaFocusLost
        if(txtDatumRodjenja.getText().isEmpty()){
            txtDatumRodjenja.setBackground(new Color(255, 168, 168));
        }else{
            Date datum = null;
            SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
        
            try {
                datum = sdf.parse(txtDatumRodjenja.getText());
            } catch (ParseException ex) {
                txtDatumRodjenja.setBackground(new Color(255, 168, 168));
                return;
            }
            txtDatumRodjenja.setBackground(Color.white);
        } 
    }//GEN-LAST:event_txtDatumRodjenjaFocusLost

    private void txtOpisFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtOpisFocusLost
        if(txtOpis.getText().isEmpty()){
            txtOpis.setBackground(new Color(255, 168, 168));
        }else{
            txtOpis.setBackground(Color.white);
        }
    }//GEN-LAST:event_txtOpisFocusLost

    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(formaUbaciiGlumca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(formaUbaciiGlumca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(formaUbaciiGlumca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(formaUbaciiGlumca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new formaUbaciiGlumca().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnOdustani;
    private javax.swing.JLabel btnUbaci;
    private javax.swing.JComboBox cbPol;
    private javax.swing.JComboBox cbPopularnost;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtAdresa;
    private javax.swing.JTextField txtDatumRodjenja;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextArea txtOpis;
    private javax.swing.JTextField txtPrezime;
    // End of variables declaration//GEN-END:variables

    private void popuniKombo() {
        cbPol.removeAllItems();
        cbPol.addItem("musko");
        cbPol.addItem("zensko");
        
        cbPopularnost.removeAllItems();
        ArrayList<Popularnost> pop = KontrolerKorisnickogInterfejsa.getInstanca().vratiPopularnost();
        for (Popularnost p : pop) {
            cbPopularnost.addItem(p);
        }
    }
}
